feat: refactor & update repo
gnolang/awesome-gno pull request #57
Opened 2024-08-11 13:00 UTC by leohhhn

TODO

2024-09-19 11:51 UTC, salmad3 requested changes

2024-09-19 11:51 UTC, salmad3 commented on README.md
> +This is the place where awesome apps, frameworks, libraries, software and resources
```suggestion
This repository is a hub for apps, frameworks, libraries, and resources.
```

2024-09-19 11:51 UTC, salmad3 commented on README.md
> +related to Gno & gno.land converge. The purpose of this repository is two-fold:
```suggestion
related to Gno & gno.land. It serves two main purposes:
```

2024-09-19 11:51 UTC, salmad3 commented on README.md
> +1. Firstly, it is a place for newcomers to see what is happening in gno.land,
```suggestion

1. It’s a place for newcomers to explore what's happening on gno.land.
```

2024-09-19 11:51 UTC, salmad3 commented on README.md
> +2. Secondly, it is a place open for everyone to share their [gno.land](https://gno.land)
```suggestion
2. It’s a space for everyone to publicly share their [gno.land](https://gno.land) projects.
```

2024-09-19 11:51 UTC, salmad3 commented on README.md
> +efforts & work, publicly. Everyone is welcome to open PRs, which will be reviewed
```suggestion
  > All are welcome to submit PRs, which will be reviewed and merged if they add value to the resource list.
```

2024-09-19 11:51 UTC, salmad3 commented on README.md
> +This is the place where awesome apps, frameworks, libraries, software and resources
A bit more standard and also to avoid using "the place" in multiple spots.

2024-09-19 11:51 UTC, salmad3 commented on README.md
> +_Some things in this repository might be outdated. We welcome any PRs that will
I think better to mention that we're actively updating with the latest resources.

2024-09-19 11:51 UTC, salmad3 commented on README.md
> +2. [gno.land networks](#gnoland-networks)
```suggestion
2. [gno.land Networks](#gnoland-networks)
```

2024-09-19 11:51 UTC, salmad3 commented on README.md
> +- [gno monorepo](https://github.com/gnolang/gno) - Main repo of the project, containing the core libraries, tools, and example Gno code.
```suggestion
- [gno monorepo](https://github.com/gnolang/gno) - The official core repo of the project, containing the core libraries, tools, and example Gno code.
```

2024-09-19 11:51 UTC, salmad3 commented on README.md
> +- [Official Documentation](https://docs.gno.land)
```suggestion
- [docs.gno.land](https://docs.gno.land) - The official docs of gno.land.
```

2024-09-19 11:51 UTC, salmad3 commented on README.md
> +- [gno.land](https://gno.land/) - The official website of the project.
```suggestion
- [gno.land](https://gno.land/) - The official website of gno.land.
```

2024-09-19 11:51 UTC, salmad3 commented on README.md
> +- [Master README](https://github.com/gnolang/gno#readme)
Needed?

2024-09-19 11:51 UTC, salmad3 commented on README.md
> +- [Plan](https://github.com/gnolang/gno/blob/master/PLAN.md)
```suggestion
- [Plan](https://github.com/gnolang/gno/blob/master/PLAN.md) - The foundational plan for gno.land.
```

2024-09-19 11:51 UTC, salmad3 commented on README.md
> +- [Philosophy](https://github.com/gnolang/gno/blob/master/PHILOSOPHY.md)
```suggestion
- [Philosophy](https://github.com/gnolang/gno/blob/master/PHILOSOPHY.md) - The fundamental philosophies of gno.land.
```

2024-09-19 11:51 UTC, salmad3 commented on README.md
> +- [staging.gno.land](https://staging.gno.land/) - Staging environment, reset periodically.
```suggestion
- [staging.gno.land](https://staging.gno.land/) - A staging environment for gno.land which resets periodically.
```

2024-09-19 11:51 UTC, salmad3 commented on README.md
> +- [test4.gno.land](https://test4.gno.land/) - Latest official multi-node stable testnet environment, released in July 2024.
```suggestion
- [test4.gno.land](https://test4.gno.land/) - The latest stable testnet environment, released in July 2024. Test4 is the first multi-node testnet of gno.land.
```

2024-09-19 11:51 UTC, salmad3 commented on README.md
> +- [GnoStudio Connect](https://gno.studio/connect) - A tool that makes interaction with Gno applications simple.
```suggestion
- [Gno Studio Connect](https://gno.studio/connect) - A tool that makes interaction with Gno applications simple.
```

2024-09-19 11:51 UTC, salmad3 commented on README.md
> +- [Gno Playground](https://play.gno.land/) - An online Gno editor that allows for quick testing, deploying, and sharing of Gno code, modeled after the Go Playground.
maybe list playground first

2024-09-19 11:51 UTC, salmad3 commented on README.md
> +- [gnodev](https://github.com/gnolang/gno/tree/master/contribs/gnodev) - Your Gno development companion, used for Gno development locally.
```suggestion
- [gnodev](https://github.com/gnolang/gno/tree/master/contribs/gnodev) - Your Gno development companion, used for local Gno development.
```

2024-09-19 11:51 UTC, salmad3 commented on README.md
> +- [GnoScan](http://gnoscan.io/) - Gnoscan, a gno.land blockchain explorer, making on-chain data legible and intuitive for everyone.
```suggestion
- [GnoScan](http://gnoscan.io/) - A gno.land blockchain explorer, making on-chain data legible and intuitive for everyone.
```

2024-09-19 11:51 UTC, salmad3 commented on README.md
> +- [GnoScan](http://gnoscan.io/) - Gnoscan, a gno.land blockchain explorer, making on-chain data legible and intuitive for everyone.
Latter half of sentence needs fixing or can probably just remove.

2024-09-19 11:51 UTC, salmad3 commented on README.md
> +- [Supernova](https://github.com/gnolang/supernova) - Stress testing tool for the Gno Tendermint2 blockchain.
```suggestion
- [Supernova](https://github.com/gnolang/supernova) - A stress testing tool for the Gno Tendermint2 blockchain.
```

2024-09-19 11:51 UTC, salmad3 commented on README.md
> +- [Supernova](https://github.com/gnolang/supernova) - Stress testing tool for the Gno Tendermint2 blockchain.
As a user I'd probably be asking what's the difference between "gno.land" and the "gno.land tm2 blockchain".

2024-09-19 11:51 UTC, salmad3 commented on README.md
> +- [Gno Extension for VS Code](https://marketplace.visualstudio.com/items?itemName=harry-hov.gno) - Rich Gno support for Visual Studio Code.
Instead of rich support, how about we state highlights of what's available today.

2024-09-19 11:51 UTC, salmad3 commented on README.md
> +- [Gno-mode for Emacs](https://gist.github.com/gfanton/6e233656dfeabd7a46f21f7507b6b311) - Major mode for editing GNO files in Emacs, based on go-mode. Work in progress.
```suggestion
- [Gno-mode for Emacs](https://gist.github.com/gfanton/6e233656dfeabd7a46f21f7507b6b311) - Major mode for editing Gno files in Emacs, based on go-mode. Work in progress.
```

2024-09-19 11:51 UTC, salmad3 commented on README.md
> +- [Gno By Example](https://gno-by-example.com) - Tutorials and code snippets for learning Gno.
```suggestion
- [Gno By Example](https://gno-by-example.com) - Interactive tutorials and code snippets for learning Gno through real-time examples.
```

2024-09-19 11:51 UTC, salmad3 commented on README.md
> +- [Getting Started](https://github.com/gnolang/getting-started) - Get started with your first Gno Realm easily with this repo.
Should follow the tone in the other points.

2024-09-19 11:51 UTC, salmad3 commented on README.md
> +- [Gno Chinese Station](https://www.gnoland.cn) - A website for Chinese Developers, providing tutorials, documents, and gno news.
```suggestion
- [Gno Chinese Station](https://www.gnoland.cn) - A website for Chinese developers, providing tutorials, resources, and Gno news.
```

2024-09-19 11:51 UTC, salmad3 commented on README.md
> +- [Gno Basics](https://github.com/moul/gno-basics) - Simple examples of Gno contracts.
```suggestion
- [Gno Basics](https://github.com/moul/gno-basics) - Simple and common examples of Gno realms.
```

2024-09-19 11:51 UTC, salmad3 commented on README.md
> +- [Hello Gno!](https://github.com/xplrz/gnoland-workshop) - Step-by-step workshop to learn Gno and gno.land features.
```suggestion
- [Hello Gno!](https://github.com/xplrz/gnoland-workshop) - A step-by-step workshop on Gno and gno.land's main features.
```

2024-09-19 11:51 UTC, salmad3 commented on README.md
> +- [From Zero to gno.land Hero](https://github.com/leohhhn/gno-fzgh/blob/main/README.md) - A complete 0 to 100 tutorial on your first dApp in gno.land.
```suggestion
- [From Zero to gno.land Hero](https://github.com/leohhhn/gno-fzgh/blob/main/README.md) - A complete 0 to 1 tutorial on building your first dApp in gno.land.
```

2024-09-19 12:58 UTC, salmad3 requested changes
What do you think about organizing the links into tables?

2024-09-19 13:37 UTC, leohhhn commented on README.md
> +- [Master README](https://github.com/gnolang/gno#readme)
I guess not; the monorepo link leads to it anyways.

2024-09-19 14:49 UTC, leohhhn commented on README.md
> +_Some things in this repository might be outdated. We welcome any PRs that will
WDYM exactly? I think it's still good to mention that things can be outdated (as some of them are).

2024-09-19 22:16 UTC, salmad3 commented on README.md
> +_Some things in this repository might be outdated. We welcome any PRs that will
I suppose since we're updating them now, they should be considered 'up to date.' Those that are primarily for reference and known to be outdated can be categorized as such.

2024-09-19 22:16 UTC, salmad3 commented on README.md
> +- [Master README](https://github.com/gnolang/gno#readme)
```suggestion
```

2024-09-20 08:07 UTC, leohhhn commented on README.md
> +_Some things in this repository might be outdated. We welcome any PRs that will
[b2a1860](https://github.com/gnolang/awesome-gno/pull/57/commits/b2a1860d88319d8b19c6d9928461359dd95edb23)

2024-09-20 08:07 UTC, leohhhn commented on README.md
> +- [Master README](https://github.com/gnolang/gno#readme)
Rm'd at your suggestion convo

2024-09-20 08:15 UTC, michelleellen commented on README.md
> +- [Gnoswap](https://github.com/gnoswap-labs/gnoswap) - the first DEX built on gno.land (currently in beta).
Consider adding dSocial and Gno Native Kit?

2024-09-20 08:15 UTC, michelleellen commented on README.md
>  We will keep some pull requests open if we're not sure whether those libraries are awesome. You could [vote for them](https://github.com/gnolang/awesome-gno/pulls) by adding :+1: to them.
What do you think about adding our event calendar link so people coming here can add all of them like office hours, spotlight, and workshops?

2024-09-20 12:15 UTC, leohhhn commented on README.md
> +- [Gno Playground](https://play.gno.land/) - An online Gno editor that allows for quick testing, deploying, and sharing of Gno code, modeled after the Go Playground.
[7c4dd58](https://github.com/gnolang/awesome-gno/pull/57/commits/7c4dd586399d50dece7b7acb7811bb93e8d4100e)

2024-09-20 12:15 UTC, leohhhn commented on README.md
> +- [Gno Extension for VS Code](https://marketplace.visualstudio.com/items?itemName=harry-hov.gno) - Rich Gno support for Visual Studio Code.
[b57ddb3](https://github.com/gnolang/awesome-gno/pull/57/commits/b57ddb3d5a4d95b066c8ba345d79f7535619c194)

2024-09-20 12:17 UTC, leohhhn commented on README.md
>  * [Start Writing a Realm](https://docs.onbloc.xyz/tutorials/start-writing-a-realm)
Moved it down to the archive section

2024-09-20 12:17 UTC, leohhhn commented on README.md
> +- [Gnoswap](https://github.com/gnoswap-labs/gnoswap) - the first DEX built on gno.land (currently in beta).
I wanted to invite the partners to do the addition themselves

2024-09-20 12:34 UTC, leohhhn commented on README.md
>  We will keep some pull requests open if we're not sure whether those libraries are awesome. You could [vote for them](https://github.com/gnolang/awesome-gno/pulls) by adding :+1: to them.
Added the calendar!

2024-09-20 12:36 UTC, thehowl approved these changes

2024-09-20 12:36 UTC, thehowl commented on README.md
maybe add status.gnoteam.com

2024-09-20 12:46 UTC, leohhhn commented on README.md
[26b7d2b](https://github.com/gnolang/awesome-gno/pull/57/commits/26b7d2bec89a8d165cc0e032c1b1e336a7b96a57)

2024-09-20 12:49 UTC, merged